### ISSUE TITLE
Allow the user to specify the version as an argument

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/action-fuel-toolchain#17]
# Summary

The action works off of [fuelup](https://github.com/FuelLabs/fuelup) which currently does not allow the user to specify the version they would like to use.

Once https://github.com/FuelLabs/fuelup/issues/46 is implemented this action should be updated to take an argument which specifies the version that a user would like to use otherwise it should default to the `latest` release.

**Comment by bingcicle** [comment]
This should be unblocked very soon once v0.3.0 of fuelup is released: https://github.com/FuelLabs/fuelup/pull/131
